import { apiClient } from './http.js';

const unwrap = (response) => response.data?.data ?? response.data;

const withParams = (params) => ({ params });

// Gom API module BE de cac trang Admin dung chung mot contract.
export const adminModulesApi = {
    listSubjects: () => apiClient.get('/subjects').then(unwrap),
    listSubjectProposals: () => apiClient.get('/subject-proposals').then(unwrap),
    createSubjectProposal: (payload) => apiClient.post('/subject-proposals', payload).then(unwrap),
    updateSubjectProposal: (publicId, payload) => apiClient.patch(`/subject-proposals/${publicId}`, payload).then(unwrap),
    deleteSubjectProposal: (publicId) => apiClient.delete(`/subject-proposals/${publicId}`).then(unwrap),
    resubmitSubjectProposal: (publicId) => apiClient.post(`/subject-proposals/${publicId}/resubmit`).then(unwrap),
    submitSubjectProposal: (publicId) => apiClient.post(`/subject-proposals/${publicId}/submit`).then(unwrap),
    trainingReviewSubject: (publicId, payload) => apiClient.post(`/subject-proposals/${publicId}/training-review`, payload).then(unwrap),
    principalReviewSubject: (publicId, payload) => apiClient.post(`/subject-proposals/${publicId}/principal-review`, payload).then(unwrap),
    updateSubject: (publicId, payload) => apiClient.patch(`/subjects/${publicId}`, payload).then(unwrap),
    updateSubjectStatus: (publicId, status) => apiClient.patch(`/subjects/${publicId}/status`, { status }).then(unwrap),
    deleteSubject: (publicId) => apiClient.delete(`/subjects/${publicId}`).then(unwrap),
    listSubjectRestoreRequests: () => apiClient.get('/subject-restore-requests').then(unwrap),
    createSubjectRestoreRequest: (publicId, payload) => apiClient.post(`/subjects/${publicId}/restore-requests`, payload).then(unwrap),
    reviewSubjectRestoreRequest: (publicId, payload) => apiClient.post(`/subject-restore-requests/${publicId}/review`, payload).then(unwrap),
    listClassProposals: () => apiClient.get('/class-proposals').then(unwrap),
    createClassProposal: (payload) => apiClient.post('/class-proposals', payload).then(unwrap),
    reviewClassProposal: (publicId, payload) => apiClient.post(`/class-proposals/${publicId}/review`, payload).then(unwrap),
    generateClassesFromProposal: (publicId) => apiClient.post(`/class-proposals/${publicId}/generate-classes`).then(unwrap),
    listClasses: () => apiClient.get('/classes').then(unwrap),
    updateClass: (publicId, payload) => apiClient.patch(`/classes/${publicId}`, payload).then(unwrap),
    listDepartments: () => apiClient.get('/departments').then(unwrap),
    createDepartment: (payload) => apiClient.post('/departments', payload).then(unwrap),
    updateDepartment: (publicId, payload) => apiClient.patch(`/departments/${publicId}`, payload).then(unwrap),
    deleteDepartment: (publicId) => apiClient.delete(`/departments/${publicId}`).then(unwrap),
    classContent: (classPublicId) => apiClient.get(`/learning/classes/${classPublicId}/content`).then(unwrap),
    createLearningSection: (payload) => apiClient.post('/learning/sections', payload).then(unwrap),
    updateLearningSection: (publicId, payload) => apiClient.patch(`/learning/sections/${publicId}`, payload).then(unwrap),
    deleteLearningSection: (publicId) => apiClient.delete(`/learning/sections/${publicId}`).then(unwrap),
    createLearningLesson: (payload) => apiClient.post('/learning/lessons', payload).then(unwrap),
    updateLearningLesson: (publicId, payload) => apiClient.patch(`/learning/lessons/${publicId}`, payload).then(unwrap),
    deleteLearningLesson: (publicId) => apiClient.delete(`/learning/lessons/${publicId}`).then(unwrap),
    reorderLearningContent: (classPublicId, payload) => apiClient.patch(`/learning/classes/${classPublicId}/content/reorder`, payload).then(unwrap),
    createLearningAssessment: (payload) => apiClient.post('/learning/assessments', payload).then(unwrap),
    learningAssessmentDetail: (publicId) => apiClient.get(`/learning/assessments/${publicId}`).then(unwrap),
    updateLearningAssessment: (publicId, payload) => apiClient.patch(`/learning/assessments/${publicId}`, payload).then(unwrap),
    replaceLearningAssessmentQuestions: (publicId, questions) => apiClient.put(`/learning/assessments/${publicId}/questions`, { questions }).then(unwrap),
    publishLearningAssessment: (publicId, isPublished) => apiClient.patch(`/learning/assessments/${publicId}/publish`, { isPublished }).then(unwrap),
    deleteLearningAssessment: (publicId) => apiClient.delete(`/learning/assessments/${publicId}`).then(unwrap),
    createLearningQuestion: (payload) => apiClient.post('/learning/questions', payload).then(unwrap),
    classAssessments: (classPublicId) => apiClient.get(`/learning/classes/${classPublicId}/assessments`).then(unwrap),
    assessmentAttempts: (assessmentPublicId) => apiClient.get(`/learning/assessments/${assessmentPublicId}/attempts`).then(unwrap),
    gradeAnswer: (answerId, payload) => apiClient.patch(`/learning/answers/${answerId}/grade`, payload).then(unwrap),
    classGradebook: (classPublicId) => apiClient.get(`/grades/classes/${classPublicId}/gradebook`).then(unwrap),
    finalizeClass: (classPublicId) => apiClient.post(`/grades/classes/${classPublicId}/finalize`).then(unwrap),
    judgeLanguages: () => apiClient.get('/learning/judge0/languages').then(unwrap),
    listSettings: () => apiClient.get('/system-settings').then(unwrap),
    updateSetting: (key, payload) => apiClient.patch(`/system-settings/${key}`, payload).then(unwrap),
    reloadSettings: () => apiClient.post('/system-settings/reload').then(unwrap),
    testRedis: () => apiClient.post('/system-settings/redis/test').then(unwrap),
    testMail: (recipient) => apiClient.post('/system-settings/mail/test', { recipient }).then(unwrap),
    listAuditLogs: (params) => apiClient.get('/audit-logs', withParams(params)).then((response) => response.data),
    listAnnouncements: (params) => apiClient.get('/announcements', withParams(params)).then(unwrap),
    announcementFeed: () => apiClient.get('/announcements/feed').then(unwrap),
    createAnnouncement: (payload) => apiClient.post('/announcements', payload).then(unwrap),
    updateAnnouncement: (publicId, payload) => apiClient.patch(`/announcements/${publicId}`, payload).then(unwrap),
    publishAnnouncement: (publicId) => apiClient.post(`/announcements/${publicId}/publish`).then(unwrap),
    cancelAnnouncement: (publicId) => apiClient.post(`/announcements/${publicId}/cancel`).then(unwrap),
    deleteAnnouncement: (publicId) => apiClient.delete(`/announcements/${publicId}`).then(unwrap),
    listNotifications: (params = {}) => apiClient.get('/notifications', withParams({
        ...params,
        unreadOnly: params.unreadOnly ? true : undefined
    })).then((response) => response.data),
    notificationUnreadCount: () => apiClient.get('/notifications/unread-count').then(unwrap),
    markNotificationRead: (publicId) => apiClient.patch(`/notifications/${publicId}/read`).then(unwrap),
    markAllNotificationsRead: () => apiClient.patch('/notifications/read-all').then(unwrap)
};
