export const routes = {
    login: '/login',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    profile: '/profile',
    notifications: '/notifications',
    settings: '/settings',
    admin: '/admin',
    adminUsers: '/admin/users',
    adminPermissions: '/admin/permissions',
    adminAuditLogs: '/admin/audit-logs',
    adminCurriculums: '/admin/curriculums',
    adminSubjects: '/admin/subjects',
    adminClasses: '/admin/classes',
    adminLessons: '/admin/lessons',
    adminExams: '/admin/exams',
    adminGrades: '/admin/grades',
    hr: '/hr',
    hrUsers: '/hr/users',
    hrDepartments: '/hr/departments',
    hrPermissions: '/hr/permissions',
    principal: '/principal',
    principalUsers: '/principal/users',
    principalDepartments: '/principal/departments',
    principalPermissions: '/principal/permissions',
    principalProposals: '/principal/proposals',
    principalProposalHistory: '/principal/proposals/history',
    principalLessons: '/principal/lessons',
    training: '/training',
    trainingUsers: '/training/users',
    trainingDepartments: '/training/departments',
    trainingPermissions: '/training/permissions',
    trainingCurriculums: '/training/curriculums',
    trainingSubjects: '/training/subjects',
    trainingClasses: '/training/classes',
    trainingLessons: '/training/lessons',
    trainingGrades: '/training/grades',
    department: '/department',
    departmentUsers: '/department/users',
    departmentDepartments: '/department/departments',
    departmentPermissions: '/department/permissions',
    departmentProposals: '/department/proposals',
    departmentClasses: '/department/classes',
    departmentLessons: '/department/lessons',
    teacher: '/teacher',
    teacherUsers: '/teacher/users',
    teacherDepartments: '/teacher/departments',
    teacherPermissions: '/teacher/permissions',
    teacherClasses: '/teacher/classes',
    teacherLessons: '/teacher/lessons',
    teacherExams: '/teacher/exams',
    teacherGrades: '/teacher/grades',
    student: '/student',
    studentUsers: '/student/users',
    studentDepartments: '/student/departments',
    studentPermissions: '/student/permissions',
    studentRegistration: '/student/registration',
    studentClasses: '/student/classes',
    studentLessons: '/student/lessons',
    studentExams: '/student/exams',
    studentGrades: '/student/grades'
};

export const roleRoutes = {
    ADMIN: routes.admin,
    HR: routes.hr,
    PRINCIPAL: routes.principal,
    TRAINING_OFFICER: routes.training,
    DEPARTMENT_HEAD: routes.department,
    LECTURER: routes.teacher,
    STUDENT: routes.student
};

export function getDashboardRouteByRole(role) {
    return roleRoutes[role] || routes.login;
}
