ALTER TABLE `AuditLog`
    MODIFY `action` ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'ASSIGN', 'ENROLL', 'DROP', 'SUBMIT', 'GRADE', 'STATUS_CHANGE', 'USER_DEACTIVATED', 'USER_REACTIVATED', 'PERMISSION_CHANGE') NOT NULL;
